### ISSUE TITLE
Art Info

### ISSUE THREAD

**Issue by wheelhot** [michealparks/galeri-www#3]
![screen shot 2017-03-28 at 3 27 33 pm](https://cloud.githubusercontent.com/assets/12379413/24393540/18ae3618-13cb-11e7-97ac-bcc3b2f73e61.png)

Instead of just the Wikipedia Link, it'll be nice if it shows the artwork name, the age and the painter.

**Comment by michealparks** [comment]
added in [v0.0.22](https://github.com/michealparks/galeri-www/releases/tag/v0.0.22) 🎉
